const fs=require('node:fs'),path=require('node:path');
const {launch,ready,scroll,baseline}=require('./qa.cjs');
const OUT=path.join(__dirname,'verification'),rows=[];
function check(name,pass,data={}){rows.push({name,pass:!!pass,...data});console.log(pass?'PASS':'FAIL',name,JSON.stringify(data));}
async function view(p,s){await scroll(p,await p.locator(s).first().evaluate(e=>e.getBoundingClientRect().top+scrollY-170));await p.waitForTimeout(250);}
async function geometry(p){return p.evaluate(()=>{const r=s=>{const e=document.querySelector(s),b=e.getBoundingClientRect();return {w:b.width,h:b.height,x:b.x,y:b.y+scrollY,html:e.innerHTML};};return {button:document.querySelectorAll('.shop_more_button').length,copies:document.querySelectorAll('[data-motif-copy]').length,main:[...document.querySelectorAll('main>*,main section')].filter(e=>e.getBoundingClientRect().height>1).map(e=>({cls:e.className,h:e.getBoundingClientRect().height,y:e.getBoundingClientRect().y+scrollY})),detail:document.querySelector('.narrative_media')?[r('.product_title'),r('.narrative_media'),r('.craft_media')]:null};});}
(async()=>{const b=await launch();try{
 for(const name of ['shop','shop-detail']){const p=await b.newPage({viewport:{width:390,height:844}});await ready(p,name);for(const w of [767,768,767,768,1279,1280,1279,1280,390]){await p.setViewportSize({width:w,height:w<768?844:900});await scroll(p,0);await p.waitForTimeout(700);const current=await geometry(p);const fresh=await b.newPage({viewport:p.viewportSize()});await ready(fresh,name);const expected=await geometry(fresh);await fresh.close();check('boundary fresh equivalence '+name+' '+w,JSON.stringify(current)===JSON.stringify(expected),{current,expected});}await p.close();}
 for(const w of [1024,390]){const p=await b.newPage({viewport:{width:w,height:w>=768?900:844},hasTouch:true,reducedMotion:'reduce'});await ready(p,'shop');await view(p,'.motif_product_strip');const s=p.locator('.motif_product_strip');const first=await s.evaluate(e=>e.scrollLeft);await p.waitForTimeout(1500);check('no autoplay reduced motion '+w,await s.evaluate(e=>e.scrollLeft)===first);await s.focus();await p.keyboard.press('ArrowRight');check('reduced motion manual keys '+w,await s.evaluate(e=>e.scrollLeft)!==first);
 const filter=p.locator('#shop_select_button');await filter.click();await p.locator('.shop_select_option').nth(1).click();check('filter UI '+w,await p.locator('.shop_select_item').nth(1).getAttribute('aria-selected')==='true'&&(await p.locator('.shop_select_label').textContent()).trim()==='TOP');
 await p.locator('#shop_search_input').fill('Cheollik');check('search input retained '+w,await p.locator('#shop_search_input').inputValue()==='Cheollik');
 await view(p,'.motif_product_strip');await s.evaluate(e=>{const a=e.querySelector(':scope>a:not([data-motif-copy])'),c=a.getBoundingClientRect().left-e.firstElementChild.getBoundingClientRect().left;e.scrollLeft=2*c-140;});await p.waitForTimeout(300);const clone=p.locator('[data-motif-copy="0"]').last();await clone.click();await p.waitForURL('**/shop_detail/index.html');check('clone product link '+w,p.url().includes('shop_detail'));
 if(w===390){await p.evaluate(()=>document.fonts.ready);await view(p,'.product_gallery');const g=p.locator('.product_gallery'),r=await g.boundingBox(),c=await p.context().newCDPSession(p),y=r.y+Math.min(r.height/2,130);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:290,y}]});for(let i=1;i<=12;i++){await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:290-i*16,y}]});await p.waitForTimeout(24);}await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(600);check('gallery touch and alt',await g.evaluate(e=>e.scrollLeft>50&&[...e.querySelectorAll('img')].every(i=>!!i.alt)));await c.detach();}
 await p.close();}
 // Final mobile geometry and all six exact square frames, at the natural top.
 for(const w of [360,375,390,430,767]){const p=await b.newPage({viewport:{width:w,height:844}});await ready(p,'shop-detail');await p.screenshot({path:path.join(OUT,'detail-'+w+'-gallery.png')});for(const sel of ['.narrative_media','.craft_media']){await view(p,sel);await p.screenshot({path:path.join(OUT,'final-detail-'+w+'-'+sel.slice(1)+'.png')});}const v=await p.evaluate(()=>({overflow:Math.max(document.body.scrollWidth,document.documentElement.scrollWidth)-innerWidth,height:document.documentElement.scrollHeight,narrativeWidth:document.querySelector('.narrative_media').getBoundingClientRect().width,gallery:[...document.querySelectorAll('.product_gallery_item')].map(e=>{const r=e.getBoundingClientRect();return[r.width,r.height];})}));check('final detail '+w,v.overflow===0&&v.narrativeWidth<=470&&v.gallery.every(s=>Math.abs(s[0]-s[1])<.1),v);await p.close();}
 }finally{await b.close();fs.writeFileSync(path.join(OUT,'final.json'),JSON.stringify(rows,null,2));}if(rows.some(r=>!r.pass))process.exitCode=1;})().catch(e=>{console.error(e);fs.writeFileSync(path.join(OUT,'final-partial.json'),JSON.stringify(rows,null,2));process.exitCode=1;});
