const fs=require('node:fs'),path=require('node:path');
const {launch,ready,scroll}=require('./qa.cjs');
const rows=[];function check(name,pass,data={}){rows.push({name,pass:!!pass,...data});console.log(pass?'PASS':'FAIL',name,JSON.stringify(data));}
(async()=>{const b=await launch();try{for(const w of [1024,390]){const p=await b.newPage({viewport:{width:w,height:w>=768?900:844},hasTouch:true});await ready(p,'shop');const s=p.locator('.motif_product_strip');await scroll(p,await s.evaluate(e=>e.getBoundingClientRect().top+scrollY-330));const rect=await s.boundingBox(),c=await p.context().newCDPSession(p),x=w/2,y=rect.y+rect.height*.55,start=await p.evaluate(()=>scrollY);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=16;i++){await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y-i*10}]});await p.waitForTimeout(30);}await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(750);check('vertical touch '+w,await p.evaluate(()=>scrollY)>start+50,{start,end:await p.evaluate(()=>scrollY)});await c.detach();
 await s.focus();let focus=[];for(let i=0;i<9;i++){await p.keyboard.press('Tab');focus.push(await p.evaluate(()=>({cls:document.activeElement.className,clone:document.activeElement.hasAttribute('data-motif-copy'),href:document.activeElement.getAttribute('href')})));}check('tab originals only '+w,focus.slice(0,8).every(e=>e.cls.includes('motif_product_card')&&!e.clone)&&!focus[8].cls.includes('motif_product_card'),{focus});
 await scroll(p,await s.evaluate(e=>e.getBoundingClientRect().top+scrollY-180));const drag=await s.boundingBox();await p.mouse.move(drag.x+drag.width*.7,drag.y+drag.height*.6);await p.mouse.down();await p.mouse.move(drag.x+drag.width*.4,drag.y+drag.height*.6,{steps:10});await p.setViewportSize({width:1280,height:900});await p.waitForTimeout(400);await p.mouse.up();check('active drag exit cleanup '+w,await s.evaluate(e=>!e.classList.contains('is_dragging')&&!e.classList.contains('is_circular')&&e.children.length===8&&!e.hasAttribute('tabindex')));await p.setViewportSize({width:w,height:w>=768?900:844});await p.waitForTimeout(400);check('active drag reentry '+w,await s.evaluate(e=>e.querySelectorAll('[data-motif-copy]').length===16&&!e.classList.contains('is_dragging')));
 // The original six gallery assets/alt texts are unchanged; photograph every
 // frame at the exact same scale to review source whitespace and silhouette.
 await ready(p,'shop-detail');if(w===390){await scroll(p,0);const g=p.locator('.product_gallery');for(let i=0;i<6;i++){await g.evaluate((e,i)=>{const el=e.querySelectorAll('.product_gallery_item')[i],r=el.getBoundingClientRect(),b=e.getBoundingClientRect();e.scrollTo({left:e.scrollLeft+r.left-b.left-(e.clientWidth-r.width)/2,behavior:'instant'});},i);await p.waitForTimeout(300);await p.screenshot({path:path.join(__dirname,'verification/gallery-390-'+(i+1)+'.png')});}}
 await p.close();}}finally{await b.close();fs.writeFileSync(path.join(__dirname,'verification/inputs.json'),JSON.stringify(rows,null,2));}if(rows.some(r=>!r.pass))process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1;});
