const fs=require('node:fs'),path=require('node:path');
const {launch,ready,scroll}=require('./qa.cjs');
// Reuse the already-reviewed QA resource instrumentation, not its old page run.
const source=fs.readFileSync(path.join(__dirname,'../post-qa4-polish/resources.cjs'),'utf8');
const {instrument,sampleResources}=new Function(source.slice(source.indexOf('function instrument()'),source.indexOf('(async()=>'))+';return {instrument,sampleResources};')();
const rows=[];
async function state(p){return p.evaluate(()=>({clones:document.querySelectorAll('[data-motif-copy]').length,strip:document.querySelector('.motif_product_strip')?.className,tabindex:document.querySelector('.motif_product_strip')?.getAttribute('tabindex'),triggers:window.ScrollTrigger?.getAll().length,pins:document.querySelectorAll('.pin-spacer').length,gallery:document.querySelectorAll('.product_gallery_item').length,stage:document.querySelectorAll('.look_stage').length,title:document.querySelector('.product_title')?.innerHTML,paragraph:document.querySelector('.narrative_copy>p')?.innerHTML}));}
(async()=>{const b=await launch();try{for(const name of ['shop','shop-detail']){const p=await b.newPage({viewport:{width:1920,height:1080}});await p.addInitScript(instrument);await ready(p,name);const samples=[];for(let round=0;round<3;round++)for(const w of [1920,1024,390,1024,1920]){await p.setViewportSize({width:w,height:w>=1280?1080:w>=768?900:844});await scroll(p,0);await p.waitForTimeout(1400);samples.push({round,w,...await state(p),...await sampleResources(p)});}
 const start=samples[0],ends=samples.filter(s=>s.w===1920),countsPass=ends.every(s=>Object.keys(start.steady).every(k=>s.steady[k]<=start.steady[k])),statesPass=samples.every(s=>name==='shop'?(s.w<1280?s.clones===16:s.clones===0&&s.tabindex===null):(s.gallery===6&&s.stage===(s.w<1280?1:0)&&((s.w<768)===!s.title.includes('<br>'))));
 const compact=samples.filter(s=>s.w===390),compactPass=compact.every(s=>Object.keys(compact[0].steady).every(k=>s.steady[k]<=compact[0].steady[k]));rows.push({name,pass:countsPass&&compactPass&&statesPass,countsPass,compactPass,statesPass,samples});console.log(name,rows.at(-1).pass,JSON.stringify(samples.map(s=>({w:s.w,round:s.round,steady:s.steady,clones:s.clones}))));await p.close();}
 }finally{await b.close();fs.writeFileSync(path.join(__dirname,'verification/lifecycle.json'),JSON.stringify(rows,null,2));}if(rows.some(r=>!r.pass))process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1;});
