const fs=require('node:fs'),path=require('node:path');
const {launch,ready,scroll,baseline,walk}=require('./qa.cjs');
const OUT=path.join(__dirname,'verification');fs.mkdirSync(OUT,{recursive:true});
const results=[];
function check(name,pass,data={}){results.push({name,pass:!!pass,...data});console.log(pass?'PASS':'FAIL',name,JSON.stringify(data));}
async function view(p,s){await scroll(p,await p.locator(s).evaluate(e=>e.getBoundingClientRect().top+scrollY-180));await p.waitForTimeout(300);}
async function shot(p,n){await p.screenshot({path:path.join(OUT,n+'.png')});}
async function metrics(p){return p.evaluate(()=>({height:document.documentElement.scrollHeight,geometry:[...document.querySelectorAll('main *,main')].filter(e=>e.checkVisibility()&&e.getBoundingClientRect().width&&e.getBoundingClientRect().height).map(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {tag:e.tagName,cls:e.className,x:r.x,y:r.y+scrollY,w:r.width,h:r.height,font:s.fontSize,border:s.border,html:e.matches('p,h1,h2')?e.innerHTML:null};}),triggers:window.ScrollTrigger?.getAll().map(t=>({start:t.start,end:t.end,pin:!!t.pin}))}));}
async function regression(b){
 for(const n of ['shop','shop-detail'])for(const w of (n==='shop'?[1920,1280]:[1920,1280,1279,1024,768])){
 const values=[];for(const old of [true,false]){const p=await b.newPage({viewport:{width:w,height:w>=1280?1080:900}});if(old)await baseline(p);await ready(p,n);await walk(p);values.push(await metrics(p));await p.close();}
 const[a,z]=values,diffs=[];if(a.height!==z.height)diffs.push({height:[a.height,z.height]});if(a.geometry.length!==z.geometry.length)diffs.push({nodes:[a.geometry.length,z.geometry.length]});
 a.geometry.forEach((v,i)=>{const q=z.geometry[i];if(!q||v.tag!==q.tag||v.cls!==q.cls||v.font!==q.font||v.html!==q.html||v.border!==q.border||['x','y','w','h'].some(k=>Math.abs(v[k]-q[k])>1))diffs.push({before:v,after:q});});
 if(JSON.stringify(a.triggers)!==JSON.stringify(z.triggers))diffs.push({triggers:[a.triggers,z.triggers]});check('locked baseline '+n+' '+w,!diffs.length,{diffs});
 }
}
async function widths(b){for(const n of ['shop','shop-detail']){const p=await b.newPage({viewport:{width:1920,height:1080}}),errors=[];p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.addInitScript(()=>addEventListener('unhandledrejection',e=>console.error('unhandled '+e.reason)));await ready(p,n);
 for(const w of [1920,1280,1279,1024,768,767,430,390,375,360]){
 await p.setViewportSize({width:w,height:w>=1280?1080:w>=768?900:844});await scroll(p,0);await p.waitForTimeout(650);await p.evaluate(()=>{document.documentElement.style.overflowX='visible';document.body.style.overflowX='visible';});let overflow=0;
 for(let f=0;f<=1;f+=.125){await scroll(p,await p.evaluate(f=>f*(document.documentElement.scrollHeight-innerHeight),f));overflow=Math.max(overflow,await p.evaluate(()=>Math.max(document.body.scrollWidth,document.documentElement.scrollWidth)-document.documentElement.clientWidth));}
 const data=await p.evaluate(()=>({height:document.documentElement.scrollHeight,broken:[...document.images].filter(e=>e.complete&&!e.naturalWidth&&e.getAttribute('src')).map(e=>e.src),sections:[...document.querySelectorAll('main>*,main section')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&(r.left< -1||r.right>innerWidth+1);}).map(e=>e.className)}));check('width '+n+' '+w,overflow===0&&!data.broken.length&&!data.sections.length,{overflow,...data});
 await p.evaluate(()=>{document.documentElement.style.removeProperty('overflow-x');document.body.style.removeProperty('overflow-x');});
 if(n==='shop'){
 const v=await p.evaluate(()=>{const s=document.querySelector('.motif_product_strip'),button=document.querySelector('.shop_more_button'),r=button.getBoundingClientRect(),axis=button.parentElement.getBoundingClientRect();return {center:Math.abs(r.x+r.width/2-axis.x-axis.width/2),clones:s.querySelectorAll('[data-motif-copy]').length,bar:getComputedStyle(s).scrollbarWidth,originals:s.querySelectorAll(':scope>a:not([data-motif-copy])').length};});check('Shop scope '+w,(w>=1280?v.clones===0:v.clones===16&&v.center<.5&&v.bar==='none')&&v.originals===8,v);
 }else if(w<768){const v=await p.evaluate(()=>{const box=s=>{const r=document.querySelector(s).getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom}};return{gallery:[...document.querySelectorAll('.product_gallery_item')].map(e=>{const r=e.getBoundingClientRect();return{w:r.width,h:r.height,fit:getComputedStyle(e.querySelector('img')).objectFit};}),br:document.querySelector('.product_title').querySelectorAll('br').length,title:document.querySelector('.product_title').textContent,caption:document.querySelector('.narrative_main_image figcaption').checkVisibility(),main:box('.narrative_main_image'),edition:box('.edition_card'),floral:box('.narrative_media_row>img'),craft:box('.craft_main_image'),thread:box('.craft_media_row>img'),weave:box('.weave_card'),borders:[...document.querySelectorAll('.craft_main_image,.craft_media_row>img')].map(e=>{const s=getComputedStyle(e);return[s.borderWidth,s.borderStyle,s.borderColor,s.borderRadius]})};});check('Detail mobile layout '+w,v.gallery.every(g=>Math.abs(g.w-g.h)<1&&g.fit==='contain')&&!v.br&&!v.caption&&v.main.x>v.edition.x&&v.edition.y<v.floral.y&&Math.abs(v.main.right-(w-24))<5&&v.craft.x<v.thread.x&&v.thread.y<v.weave.y&&v.borders.every(s=>s.join()==='0px,none,rgb(255, 253, 249),0px'),v);if([390,360,767].includes(w)){await view(p,'.narrative_media');await shot(p,'detail-'+w+'-narrative');await view(p,'.craft_media');await shot(p,'detail-'+w+'-craft');}}
 }
 check('errors '+n,!errors.length,{errors});await p.close();}}
async function gesture(p,dir,touch){const e=p.locator('.motif_product_strip');await view(p,'.motif_product_strip');const r=await e.boundingBox(),x=dir>0?r.x+r.width*.8:r.x+r.width*.2,y=r.y+r.height*.6,end=x-dir*Math.min(r.width*.6,420);if(touch){const c=await p.context().newCDPSession(p);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=16;i++){await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+(end-x)*i/16,y}]});await p.waitForTimeout(24);}await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await c.detach();}else{await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(end,y,{steps:18});await p.mouse.up();}await p.waitForTimeout(600);}
async function loop(b){for(const w of [1024,390,360]){
 const p=await b.newPage({viewport:{width:w,height:w>=768?900:844},hasTouch:true});await ready(p,'shop');await view(p,'.motif_product_strip');const s=p.locator('.motif_product_strip');
 const v=await s.evaluate(e=>({a11y:[...e.querySelectorAll('[data-motif-copy]')].every(n=>n.getAttribute('aria-hidden')==='true'&&n.tabIndex===-1&&!n.id&&![...n.querySelectorAll('[tabindex]')].some(i=>i.tabIndex>=0)),ids:[...document.querySelectorAll('[id]')].map(e=>e.id),children:e.children.length}));check('clone accessibility '+w,v.a11y&&new Set(v.ids).size===v.ids.length&&v.children===24,v);
 // Compare every visible image's source/rect immediately before and after the
 // hidden relocation, on both sides of the same logical boundary.
 for(const dir of [-1,1]){const state=await s.evaluate(async(e,dir)=>{const orig=e.querySelector(':scope>a:not([data-motif-copy])'),cycle=orig.getBoundingClientRect().left-e.firstElementChild.getBoundingClientRect().left;const frame=()=>{const b=e.getBoundingClientRect();return [...e.querySelectorAll('img')].map(n=>{const r=n.getBoundingClientRect();return{src:n.src,x:r.x,y:r.y,w:r.width,h:r.height}}).filter(r=>r.x<b.right&&r.x+r.w>b.left);};e.scrollLeft=dir<0?cycle-18:2*cycle+18;const before=frame();await new Promise(r=>setTimeout(r,180));return{cycle,before,after:frame(),left:e.scrollLeft};},dir);check('identical seam '+w+' '+dir,JSON.stringify(state.before)===JSON.stringify(state.after),state);await shot(p,'shop-'+w+'-seam-'+dir);}
 for(const touch of [false,true])for(const dir of [1,-1]){
 const start=await s.evaluate((e,dir)=>{const o=e.querySelector(':scope>a:not([data-motif-copy])'),c=o.getBoundingClientRect().left-e.firstElementChild.getBoundingClientRect().left;e.scrollLeft=dir>0?2*c-60:c+60;return{cycle:c,left:e.scrollLeft};},dir);await p.waitForTimeout(50);await gesture(p,dir,touch);const end=await s.evaluate(e=>e.scrollLeft);const distance=dir>0?(end-start.left+start.cycle)%start.cycle:(start.left-end+start.cycle)%start.cycle;check('boundary '+(touch?'touch':'mouse')+' '+w+' '+dir,distance>80&&distance<start.cycle*.65,{start,end,distance});}
 await view(p,'.motif_product_strip');const r=await s.boundingBox();await p.mouse.move(r.x+r.width/2,r.y+r.height/2);let start=await s.evaluate(e=>e.scrollLeft);await p.mouse.wheel(450,0);await p.waitForTimeout(500);check('horizontal trackpad '+w,Math.abs(await s.evaluate(e=>e.scrollLeft)-start)>100);const y=await p.evaluate(()=>scrollY);await p.mouse.wheel(0,320);await p.waitForTimeout(1000);check('vertical wheel '+w,await p.evaluate(()=>scrollY)>y+50);
 await view(p,'.motif_product_strip');await s.focus();start=await s.evaluate(e=>e.scrollLeft);await p.keyboard.press('ArrowRight');await p.waitForTimeout(200);check('keyboard '+w,await s.evaluate(e=>e.scrollLeft)!==start);
 await p.close();
}}
async function functions(b){for(const w of [390,1024,1920]){const p=await b.newPage({viewport:{width:w,height:w>=1280?1080:w>=768?900:844}});await ready(p,'shop-detail');await p.locator('.color_swatch').nth(1).click();check('color '+w,await p.locator('.color_swatch').nth(1).getAttribute('aria-pressed')==='true');await p.locator('.size_button').nth(2).click();check('size '+w,await p.locator('.size_button').nth(2).getAttribute('aria-pressed')==='true');await p.locator('#add_to_cart').click();check('purchase dialog '+w,await p.locator('#purchase_complete_dialog').evaluate(e=>e.open));await p.locator('[data-dialog-close]').click();for(let i=0;i<3;i++){await p.locator('.accordion_item>button').nth(i).click();check('accordion '+w+' '+i,await p.locator('.accordion_item>button').nth(i).getAttribute('aria-expanded')==='true');}if(w<768){await view(p,'.product_gallery');await p.locator('.product_gallery').focus();await p.keyboard.press('ArrowRight');await p.waitForTimeout(600);check('gallery keyboard '+w,await p.locator('.product_gallery').evaluate(e=>e.scrollLeft)>0);}await p.close();}}
async function run(){const b=await launch();try{const mode=process.argv[2]||'all';if(mode==='all'||mode==='widths')await widths(b);if(mode==='all'||mode==='loop')await loop(b);if(mode==='all'||mode==='regression')await regression(b);if(mode==='all'||mode==='functions')await functions(b);}finally{await b.close();fs.writeFileSync(path.join(OUT,(process.argv[2]||'all')+'.json'),JSON.stringify(results,null,2));}if(results.some(r=>!r.pass))process.exitCode=1;}
run().catch(e=>{console.error(e);fs.writeFileSync(path.join(OUT,'partial.json'),JSON.stringify(results,null,2));process.exitCode=1;});
