const fs=require('node:fs');const {launch,ready,PAGES}=require('./qa.cjs');
const rows=[];
async function run(){const b=await launch();try{for(const width of [360,390,768,1024,1279]){const p=await b.newPage({viewport:{width,height:width<768?844:900}});for(const name of (process.argv[2]?process.argv[2].split(','):Object.keys(PAGES))){
 await ready(p,name);const data=await p.evaluate(({name,width})=>{
 const out=[],T=width>=768,Q=s=>document.querySelector(s),R=s=>{const e=typeof s==='string'?Q(s):s;return e?e.getBoundingClientRect():{x:0,y:0,width:0,height:0,top:0,bottom:0,left:0,right:0};},C=(id,pass,detail)=>out.push({id,width,pass:!!pass,detail}),hidden=s=>!R(s).height;
 const center=s=>R(s).x+R(s).width/2;
 if(name==='main'&&T){C('T-M1',hidden('.detail_subtitle'));C('T-M2',hidden('.promo_img'));C('T-M5',hidden('.collection_desc'));
 for(const [id,scope] of [['T-M3','.promo_bespoke_wrap'],['T-M4','.shop']]){const e=Q(scope),a=e.querySelector('.promo_lead'),c=e.querySelector('.main_button'),x=R(a),y=R(c);C(id,y.x>=x.right&&Math.abs((y.y+y.height/2)-(x.y+x.height/2))<4&&y.height>=44,{lead:{x:x.x,y:x.y,w:x.width,h:x.height},cta:{x:y.x,y:y.y,w:y.width,h:y.height}});}
 const a=R('.promo_shop_video'),d=R('.promo_bespoke_video');C('T-M6',Math.abs(a.width-d.width)<2&&Math.abs(a.height-d.height)<2,{shop:[a.width,a.height],bespoke:[d.width,d.height]});}
 if(name==='brand'){
 const rail=Q('.mood_slides'),v=R(rail),slides=[...rail.children],visible=slides.filter(s=>{const r=R(s);return r.right>v.left+1&&r.left<v.right-1;}),slide=visible[0],img=R(slide.querySelector('img')),title=R(slide.querySelector('h3')),desc=R(slide.querySelector('.mood_slide_description'));
 C(T?'T-B2':'M-B4',img.width>=width-1,{width:img.width});C(T?'T-B3':'M-B2',visible.length===1,{visible:visible.length});
 if(T){C('T-B1',hidden('.mood_slide_caption'));C('T-B5',Math.abs(center('.tchaikim_tabs')-width/2)<2);C('T-B6',hidden('.heritage_info_title')&&hidden('.heritage_info_desc'));C('T-B9',Math.abs(center('.youngjin_handmade')-center('.youngjin_wordmark'))<2);
 const range=document.createRange();range.selectNodeContents(Q('.youngjin_wordmark'));const wr=range.getBoundingClientRect();C('T-B10',wr.width>width*.7&&wr.width<=width&&wr.x>=-1&&wr.right<=width+1,{glyphWidth:wr.width});
 }else{C('M-B1',title.bottom<=img.top+1&&img.bottom<=desc.top+1);C('M-B5',Q('.youngjin_mobile_title').textContent==='Tchai Kimyoungjin'&&hidden('.youngjin_group')&&R('.youngjin_mobile_label').y>R('.youngjin_mobile_rail').y);C('M-B6',Q('.tchaikim_mobile_title').textContent==='Tchaikim'&&R('.tchaikim_mobile_title').bottom<=R('.tchaikim_tabs').top);
 const tabs=[...document.querySelectorAll('.tchaikim_tab')].map(R),tl=Q('.tchaikim_tabs');C('M-B7',tl.scrollWidth<=tl.clientWidth+1&&tabs.every(t=>Math.abs(t.y-tabs[0].y)<1&&t.right<=width&&t.height>=44),{width:tl.clientWidth,scrollWidth:tl.scrollWidth});C('M-B8',parseFloat(getComputedStyle(Q('.heritage')).marginTop)>=48);}
 const h=R('.heritage_title'),f=R('.heritage_photos'),bt=R('.heritage_button');C(T?'T-B7':'M-B9',h.bottom<=f.top+1&&f.bottom<=bt.top+1&&Math.abs(center('.heritage_photos')-width/2)<2&&Math.abs(center('.heritage_button')-width/2)<2,{title:h.y,figure:f.y,button:bt.y});
 C(T?'T-B8':'M-B10',Math.abs(R('.mood_responsive').bottom-R('.kimyoungjin').top)<1&&getComputedStyle(Q('.mood_responsive')).backgroundColor==='rgb(88, 90, 77)',{gap:R('.kimyoungjin').top-R('.mood_responsive').bottom,gradient:getComputedStyle(Q('.mood_responsive'),'::after').backgroundImage});
 }
 if(name==='bespoke'){if(T){C('T-BS1',[...Q('.atelier_body').children].filter(e=>R(e).height>0).every(e=>e.classList.contains('atelier_button')));C('T-BS2',parseFloat(getComputedStyle(Q('.atelier_image')).marginTop)===0&&parseFloat(getComputedStyle(Q('.atelier_image')).marginLeft)===0);
 const qt=Q('.quote_text'),qc=Q('.quote_cite'),qs=getComputedStyle(qt),cs=getComputedStyle(qc);C('T-BS3',qs.textAlign==='left'&&R(qt).height/parseFloat(qs.lineHeight)<=2.2,{lines:R(qt).height/parseFloat(qs.lineHeight)});C('T-BS4',cs.textAlign==='left'&&cs.whiteSpace==='nowrap'&&R(qc).right<=width);C('T-BS5',parseFloat(getComputedStyle(Q('.process')).paddingTop)>=140);C('T-BS6',hidden('.materials_intro'));
 const ss=[...document.querySelectorAll('.materials_swatch')].map(R);C('T-BS7',ss.length===6&&Math.abs(ss[0].y-ss[2].y)<1&&ss[3].y>ss[0].bottom&&R('.materials_selected').y<ss[0].y);
 }else{C('M-BS1',hidden('.philosophy')&&!Q('.philosophy').classList.contains('is_motion_ready'));C('M-BS2',hidden('.atelier_image'));const a=R('.atelier_button'),v=R('.bespoke_hero_video');C('M-BS3',a.y>=v.bottom&&Math.abs(center('.atelier_button')-width/2)<1&&a.height>=44,{center:center('.atelier_button'),y:a.y,videoBottom:v.bottom});}}
 if(name==='reservation'&&!T){const e=Q('.bespoke_choice_grid.is_three_up'),cards=[...e.children].map(R);C('M-R1',cards.length===3&&e.scrollWidth<=e.clientWidth+1&&cards.every(c=>Math.abs(c.y-cards[0].y)<1&&c.x>=0&&c.right<=width));}
 if(name==='collection'||name==='collection-youngjin'){
 const a=R('.archive_title'),y=R('.archive_year_list'),d=R('.archive_deck'),cta=R('.archive_more');
 if(T)C('T-C2',a.bottom<=y.top+2&&y.bottom<=d.top+2&&d.bottom<=cta.top+2,{page:name,title:a.y,year:y.y,deck:d.y,cta:cta.y});
 const photos=[...document.querySelectorAll('.archive_photo')].filter(e=>R(e).width),xs=photos.map(e=>R(e).x);C(T?'T-C3':'M-C2',new Set(xs.map(Math.round)).size>1,{page:name,x:xs});
 if(!T){const title=Q('.archive_title'),range=document.createRange();range.selectNodeContents(title);C('M-C3',getComputedStyle(title).whiteSpace==='nowrap'&&title.scrollWidth<=title.clientWidth+1&&a.x>=0&&a.right<=width,{page:name,w:a.width});const ys=[...Q('.archive_year_list').children].map(R);C('M-C4',ys.every(r=>Math.abs(r.y-ys[0].y)<1&&r.right<=width&&r.x>=0),{page:name,count:ys.length});}}
if(name==='shop'){const units=Q('.garment_content');C(T?'T-S1':'M-S2',units.children.length>=4&&units.scrollWidth>units.clientWidth&&R('.garment_story_frame').height<(T?850:900),{h:R('.garment_story_frame').height});if(T){C('T-C4',hidden('.motif_video_media'),{mappedPage:'Shop — selectors absent from Collections'});C('T-C5',R('.motif_reference_image').right<R('.motif_reference_copy').left,{mappedPage:'Shop'});}else{C('M-S1',parseFloat(getComputedStyle(Q('.banner_title')).fontSize)<=30);C('M-S3',parseFloat(getComputedStyle(Q('.shop_list_title')).fontSize)<=32);C('M-S4',parseFloat(getComputedStyle(Q('.new_arrivals_section')).paddingTop)>=80);const e=Q('.motif_reference_desc'),s=getComputedStyle(e);C('M-S5',R(e).height/parseFloat(s.lineHeight)<=3.1,{lines:R(e).height/parseFloat(s.lineHeight)});C('M-S6',hidden('.motif_video_media'));}}
 if(name==='shop-detail'){C(T?'T-SD1':'M-SD6',!!Q('.look_stage')&&getComputedStyle(Q('.look_pin')).position==='absolute'&&getComputedStyle(Q('.look_caption')).position==='static');if(!T){const g=Q('.product_gallery');C('M-SD1',getComputedStyle(Q('.product_gallery_item img')).objectFit==='contain');C('M-SD2',getComputedStyle(g).scrollbarWidth==='none'&&g.scrollWidth>g.clientWidth&&g.tabIndex===0);C('M-SD3',hidden('.narrative_copy>p:first-of-type'));C('M-SD4',R('.narrative_section').height<1600&&R('.craft_section').height<1300,{narrative:R('.narrative_section').height,craft:R('.craft_section').height});const copy=Q('.craft_copy>p:not(.section_label)').textContent;C('M-SD5',['third-generation','Gyeonggi-do','80-count silk-cotton','structural weight','movement','matte depth','pleated'].every(t=>copy.includes(t)),{copy});}}
 return out;
 },{name,width});rows.push(...data);console.log(name,width,data.filter(r=>!r.pass));
 }await p.close();}}finally{await b.close();const file=__dirname+'/verification/layout-acceptance.json';const previous=process.argv[2]&&fs.existsSync(file)?JSON.parse(fs.readFileSync(file)).filter(old=>!rows.some(r=>r.id===old.id&&r.width===old.width)):[];fs.writeFileSync(file,JSON.stringify(previous.concat(rows),null,2));}}
run().catch(e=>{console.error(e);process.exitCode=1;});
