const fs=require('node:fs');const {PAGES,launch,ready,scroll,baseline}=require('./qa.cjs');
const dir=__dirname+'/verification',results=[];function check(name,pass,detail={}){results.push({name,pass:!!pass,...detail});console.log(pass?'PASS':'FAIL',name,JSON.stringify(detail));}
(async()=>{const b=await launch();try{
 for(const width of [390,1024,1920]){const p=await b.newPage({viewport:{width,height:width<768?844:width<1280?900:1080},hasTouch:width<1280});await ready(p,'shop-detail');
 await p.locator('.color_swatch').nth(1).click();check('Color '+width,await p.locator('#color_name').textContent()==='SAGE');await p.locator('.size_button').nth(2).click();check('Size '+width,await p.locator('.size_button.is_selected').textContent()==='M');await p.locator('#size_guide_toggle').click();await p.locator('.size_unit_button[data-unit="inch"]').click();check('Size guide '+width,await p.locator('#size_guide_panel').evaluate(e=>e.classList.contains('is_open')&&e.classList.contains('is_unit_inch')));
 await p.locator('#add_to_cart').click();check('Purchase modal '+width,await p.locator('#purchase_complete_dialog').evaluate(e=>e.open));await p.locator('[data-dialog-close]').click();check('Purchase focus return '+width,await p.locator('#add_to_cart').evaluate(e=>e===document.activeElement));
 for(let i=0;i<3;i++){await p.locator('.accordion_item>button').nth(i).click();check('Accordion '+width+' '+i,await p.locator('.accordion_item>button').nth(i).getAttribute('aria-expanded')==='true');}await p.screenshot({path:dir+'/detail-'+width+'-accordion.png'});
 await ready(p,'shop');await p.locator('#shop_select_button').click();await p.locator('.shop_select_option[data-category="dress"]').click();check('Shop category '+width,(await p.locator('.shop_select_label').textContent()).toLowerCase().includes('dress'));await p.locator('#shop_search_input').fill('unmatched-qa-term');await p.waitForTimeout(300);check('Shop search no cards '+width,await p.locator('.shop_grid .card_product:visible').count()===0);await p.locator('#shop_search_input').fill('');await p.close();}
 // Read-only scroll sweeps with overflow concealment removed.
 for(const width of [390,1024])for(const name of Object.keys(PAGES)){const p=await b.newPage({viewport:{width,height:width===390?844:900},hasTouch:true});await ready(p,name);const measurements=[];for(const s of PAGES[name][1]){const e=p.locator(s).first();if(!await e.count()||!await e.isVisible())continue;await scroll(p,await e.evaluate(e=>e.getBoundingClientRect().top+scrollY-90));const metric=await p.evaluate(()=>{const old=[document.body.style.overflowX,document.documentElement.style.overflowX];document.body.style.overflowX='visible';document.documentElement.style.overflowX='visible';const n=Math.max(document.body.scrollWidth,document.documentElement.scrollWidth)-innerWidth;document.body.style.overflowX=old[0];document.documentElement.style.overflowX=old[1];return n;});measurements.push({section:s,overflow:metric});}check('scroll overflow '+name+' '+width,measurements.every(m=>m.overflow<=1),{measurements});await p.close();}
 // Desktop pin compositions: actual mid-scene frames, not blank full-page runways.
 for(const name of ['main','brand','collection','collection-youngjin'])for(const phase of ['before','after']){const p=await b.newPage({viewport:{width:1920,height:1080}});if(phase==='before')await baseline(p);await ready(p,name);const scenes=await p.evaluate(()=>ScrollTrigger.getAll().filter(t=>t.pin).map(t=>({start:t.start,end:t.end,cls:t.pin.className})));for(let i=0;i<scenes.length;i++){await scroll(p,scenes[i].start+(scenes[i].end-scenes[i].start)*.55);await p.waitForTimeout(1400);await p.screenshot({path:dir+'/desktop-'+name+'-'+phase+'-'+i+'.png'});}check('Desktop scenes '+name+' '+phase,scenes.length>0,{scenes});await p.close();}
 }finally{await b.close();fs.writeFileSync(dir+'/deep.json',JSON.stringify(results,null,2));}})().catch(e=>{console.error(e);process.exitCode=1;});
