const fs=require('node:fs');const {PAGES,launch,ready,scroll}=require('./qa.cjs');
function instrument(){
 const active=new Set(),registry=new WeakMap(),nativeAdd=EventTarget.prototype.addEventListener,nativeRemove=EventTarget.prototype.removeEventListener;
 EventTarget.prototype.addEventListener=function(type,fn,options){
  if(!fn)return nativeAdd.call(this,type,fn,options);const capture=typeof options==='boolean'?options:!!options?.capture;
  let list=registry.get(this);if(!list){list=[];registry.set(this,list);}if(list.some(r=>r.live&&r.type===type&&r.fn===fn&&r.capture===capture))return;
  const r={target:this,type,fn,capture,live:true};r.wrapped=function(...args){if(options?.once){r.live=false;active.delete(r);}return typeof fn==='function'?fn.apply(this,args):fn.handleEvent(...args);};
  list.push(r);if(!options?.signal?.aborted)active.add(r);else r.live=false;
  if(options?.signal)nativeAdd.call(options.signal,'abort',()=>{r.live=false;active.delete(r);},{once:true});
  return nativeAdd.call(this,type,r.wrapped,options);
 };
 EventTarget.prototype.removeEventListener=function(type,fn,options){const capture=typeof options==='boolean'?options:!!options?.capture;const r=(registry.get(this)||[]).find(r=>r.live&&r.type===type&&r.fn===fn&&r.capture===capture);if(r){r.live=false;active.delete(r);}return nativeRemove.call(this,type,r?r.wrapped:fn,options);};
 const pending=new Set(),intervals=new Set(),frames=new Set(),set=window.setTimeout,clear=window.clearTimeout,si=window.setInterval,ci=window.clearInterval,raf=window.requestAnimationFrame,caf=window.cancelAnimationFrame;
 window.setTimeout=function(fn,delay,...args){let id=set(()=>{pending.delete(id);if(typeof fn==='function')fn(...args);},delay);pending.add(id);return id;};window.clearTimeout=function(id){pending.delete(id);return clear(id);};
 window.setInterval=function(...a){let id=si(...a);intervals.add(id);return id;};window.clearInterval=function(id){intervals.delete(id);return ci(id);};
 window.requestAnimationFrame=function(fn){let id=raf(t=>{frames.delete(id);fn(t);});frames.add(id);return id;};window.cancelAnimationFrame=function(id){frames.delete(id);return caf(id);};
 const observers={};for(const name of ['ResizeObserver','IntersectionObserver','MutationObserver']){const Native=window[name],set=new Set();observers[name]=set;window[name]=class extends Native{constructor(...a){super(...a);this.targets=new Set();}observe(target,...a){this.targets.add(target);set.add(this);return super.observe(target,...a);}unobserve(target){this.targets.delete(target);if(!this.targets.size)set.delete(this);return super.unobserve(target);}disconnect(){this.targets.clear();set.delete(this);return super.disconnect();}};}
 window.qaResources=()=>({listeners:[...active].filter(r=>r.target===window||r.target===document||r.target instanceof MediaQueryList||r.target instanceof Element&&r.target.isConnected).length,timers:pending.size,intervals:intervals.size,raf:frames.size,...Object.fromEntries(Object.entries(observers).map(([k,s])=>[k,[...s].filter(o=>[...o.targets].some(t=>t.isConnected)).length]))});
}
(async()=>{const browser=await launch(),results=[],names=Object.keys(PAGES);try{await Promise.all([0,1].map(async()=>{while(names.length){const name=names.shift(),p=await browser.newPage({viewport:{width:1920,height:1080}});await p.addInitScript(instrument);await ready(p,name);await p.waitForTimeout(2500);const start=await p.evaluate(()=>qaResources()),samples=[];for(let n=0;n<2;n++){for(const w of [1920,1024,390,1024,1920]){await p.setViewportSize({width:w,height:w>=1280?1080:w>=768?900:844});await scroll(p,0);await p.waitForTimeout(650);}await p.waitForTimeout(2500);samples.push(await p.evaluate(()=>qaResources()));}const pass=['listeners','timers','intervals','raf','ResizeObserver','IntersectionObserver','MutationObserver'].every(k=>samples.every(s=>s[k]<=start[k]));const row={name,pass,start,samples};results.push(row);console.log(JSON.stringify(row));await p.close();}}));}finally{await browser.close();fs.writeFileSync(__dirname+'/verification/resources.json',JSON.stringify(results,null,2));}})().catch(e=>{console.error(e);process.exitCode=1;});
